# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="auth.proto",
    package="todusAuth",
    syntax="proto2",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\nauth.proto\x12\ttodusAuth"$\n\x07reserve\x12\r\n\x05phone\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t"8\n\x08register\x12\r\n\x05phone\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12\x11\n\tsms_token\x18\x03 \x02(\t"\xaf\x01\n\rregister_data\x12\x0b\n\x03uid\x18\x01 \x02(\x0c\x12\x35\n\x0buserProfile\x18\x02 \x02(\x0b\x32 .todusAuth.register_data.profile\x1aZ\n\x07profile\x12\r\n\x05phone\x18\x01 \x02(\t\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\t\x12\x10\n\x08photoUrl\x18\x03 \x01(\t\x12\x0c\n\x04info\x18\x04 \x01(\t\x12\x0b\n\x03meh\x18\x05 \x01(\t"B\n\x05token\x12\r\n\x05phone\x18\x01 \x02(\t\x12\x11\n\tuser_hash\x18\x02 \x02(\x0c\x12\x17\n\x0f\x63ompilation_ver\x18\x03 \x02(\t"8\n\ntoken_data\x12\x0b\n\x03meh\x18\x01 \x02(\x05\x12\r\n\x05token\x18\x02 \x02(\x0c\x12\x0e\n\x06\x65xpire\x18\x03 \x02(\x05',
)


_RESERVE = _descriptor.Descriptor(
    name="reserve",
    full_name="todusAuth.reserve",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="phone",
            full_name="todusAuth.reserve.phone",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="id",
            full_name="todusAuth.reserve.id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=61,
)


_REGISTER = _descriptor.Descriptor(
    name="register",
    full_name="todusAuth.register",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="phone",
            full_name="todusAuth.register.phone",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="id",
            full_name="todusAuth.register.id",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="sms_token",
            full_name="todusAuth.register.sms_token",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=63,
    serialized_end=119,
)


_REGISTER_DATA_PROFILE = _descriptor.Descriptor(
    name="profile",
    full_name="todusAuth.register_data.profile",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="phone",
            full_name="todusAuth.register_data.profile.phone",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="displayName",
            full_name="todusAuth.register_data.profile.displayName",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="photoUrl",
            full_name="todusAuth.register_data.profile.photoUrl",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="info",
            full_name="todusAuth.register_data.profile.info",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="meh",
            full_name="todusAuth.register_data.profile.meh",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=207,
    serialized_end=297,
)

_REGISTER_DATA = _descriptor.Descriptor(
    name="register_data",
    full_name="todusAuth.register_data",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="uid",
            full_name="todusAuth.register_data.uid",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="userProfile",
            full_name="todusAuth.register_data.userProfile",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=2,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[
        _REGISTER_DATA_PROFILE,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=122,
    serialized_end=297,
)


_TOKEN = _descriptor.Descriptor(
    name="token",
    full_name="todusAuth.token",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="phone",
            full_name="todusAuth.token.phone",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="user_hash",
            full_name="todusAuth.token.user_hash",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="compilation_ver",
            full_name="todusAuth.token.compilation_ver",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=299,
    serialized_end=365,
)


_TOKEN_DATA = _descriptor.Descriptor(
    name="token_data",
    full_name="todusAuth.token_data",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="meh",
            full_name="todusAuth.token_data.meh",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=2,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="token",
            full_name="todusAuth.token_data.token",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=2,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="expire",
            full_name="todusAuth.token_data.expire",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=2,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=367,
    serialized_end=423,
)

_REGISTER_DATA_PROFILE.containing_type = _REGISTER_DATA
_REGISTER_DATA.fields_by_name["userProfile"].message_type = _REGISTER_DATA_PROFILE
DESCRIPTOR.message_types_by_name["reserve"] = _RESERVE
DESCRIPTOR.message_types_by_name["register"] = _REGISTER
DESCRIPTOR.message_types_by_name["register_data"] = _REGISTER_DATA
DESCRIPTOR.message_types_by_name["token"] = _TOKEN
DESCRIPTOR.message_types_by_name["token_data"] = _TOKEN_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

reserve = _reflection.GeneratedProtocolMessageType(
    "reserve",
    (_message.Message,),
    {
        "DESCRIPTOR": _RESERVE,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:todusAuth.reserve)
    },
)
_sym_db.RegisterMessage(reserve)

register = _reflection.GeneratedProtocolMessageType(
    "register",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTER,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:todusAuth.register)
    },
)
_sym_db.RegisterMessage(register)

register_data = _reflection.GeneratedProtocolMessageType(
    "register_data",
    (_message.Message,),
    {
        "profile": _reflection.GeneratedProtocolMessageType(
            "profile",
            (_message.Message,),
            {
                "DESCRIPTOR": _REGISTER_DATA_PROFILE,
                "__module__": "auth_pb2"
                # @@protoc_insertion_point(class_scope:todusAuth.register_data.profile)
            },
        ),
        "DESCRIPTOR": _REGISTER_DATA,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:todusAuth.register_data)
    },
)
_sym_db.RegisterMessage(register_data)
_sym_db.RegisterMessage(register_data.profile)

token = _reflection.GeneratedProtocolMessageType(
    "token",
    (_message.Message,),
    {
        "DESCRIPTOR": _TOKEN,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:todusAuth.token)
    },
)
_sym_db.RegisterMessage(token)

token_data = _reflection.GeneratedProtocolMessageType(
    "token_data",
    (_message.Message,),
    {
        "DESCRIPTOR": _TOKEN_DATA,
        "__module__": "auth_pb2"
        # @@protoc_insertion_point(class_scope:todusAuth.token_data)
    },
)
_sym_db.RegisterMessage(token_data)


# @@protoc_insertion_point(module_scope)
